variables:
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self

jobs:
- job: BuildAndTest
  displayName: BuildAndTest
  pool: Continuous Integration 02 - SSD - 160ACU

  steps:
  # Run PowerShell tests and publish results
  - task: PowerShell@2
    name: InvokeTests
    displayName: 'Invoke-Tests'
    inputs: 
     targetType: 'filePath'
     filePath: $(System.DefaultWorkingDirectory)/Tests/Invoke-Tests.ps1
     arguments: -CodeCoveragePath $(System.DefaultWorkingDirectory)\Scripts\*.ps1
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
     testResultsFormat: NUnit
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
     summaryFileLocation: '**/CODECOVERAGE-*.xml'
  - task: PowerShell@2
    name: OutputTests
    displayName: 'Out-TestResults'
    inputs: 
     targetType: 'filePath'
     filePath: $(System.DefaultWorkingDirectory)/Tests/Out-TestResults.ps1
     arguments: '-CoveragePercent 10'
  # Build and publish NCS.DSS.AnonymiseBackup
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish application'
    inputs:
      command: 'publish'
      projects: 'Applications\NCS.DSS.AnonymiseBackup\NCS.DSS.AnonymiseBackup.csproj'
      arguments: '-o "$(build.artifactstagingdirectory)\Artifact\NCS.DSS.AnonymiseBackupPackages\\" -c "$(BuildConfiguration)" -r "$(BuildPlatform)"'
      publishWebProjects: false
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: NCS.DSS.AnonymiseBackup'
    inputs:
      pathtoPublish: $(build.artifactstagingdirectory)\Artifact\
      artifactName: NCS.DSS.AnonymiseBackup
      publishLocation: container

