variables:
  - name: BuildPlatform
    value: 'any cpu'
  - name: BuildConfiguration
    value: 'release'
  - group: AT Shared Resources
  - group: KeyVault - dss-at-shared-kv

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    endpoint: 'GitHub (CDH)'
    ref: refs/tags/v1.14.0

jobs:
- job: BuildAndTestPS
  displayName: 'Build and Test PowerShell'
  pool: NCS - CI and CD

  steps:
  # Run PowerShell tests and publish results
  - task: PowerShell@2
    name: InvokeTests
    displayName: 'Invoke-Tests'
    inputs: 
     targetType: 'filePath'
     filePath: $(System.DefaultWorkingDirectory)/Tests/Invoke-Tests.ps1
     arguments: -CodeCoveragePath $(System.DefaultWorkingDirectory)\Scripts\*.ps1
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
     testResultsFormat: NUnit
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
     summaryFileLocation: '**/CODECOVERAGE-*.xml'
  - task: PowerShell@2
    name: OutputTests
    displayName: 'Out-TestResults'
    inputs: 
     targetType: 'filePath'
     filePath: $(System.DefaultWorkingDirectory)/Tests/Out-TestResults.ps1
     arguments: '-CoveragePercent 10'
  # Publish PowerShell artifacts
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: FunctionAppTools'
    inputs:
      pathtoPublish: FunctionAppTools
      artifactName: FunctionAppTools
      publishLocation: container
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Modules'
    inputs:
      pathtoPublish: Modules
      artifactName: Modules
      publishLocation: container 
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Scripts'
    inputs:
      pathtoPublish: Scripts
      artifactName: Scripts
      publishLocation: container  
  # Publish SQL Script artifact
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: SQLScripts'
    inputs:
      pathtoPublish: SQLScripts
      artifactName: SQLScripts
      publishLocation: container           
  # Build and publish NCS.DSS.AnonymiseBackup
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish application'
    inputs:
      command: 'publish'
      projects: 'Applications\NCS.DSS.AnonymiseBackup\NCS.DSS.AnonymiseBackup.csproj'
      arguments: '-o "$(build.artifactstagingdirectory)\Artifact\NCS.DSS.AnonymiseBackupPackages\\" -c "$(BuildConfiguration)" -r "$(BuildPlatform)"'
      publishWebProjects: false
      zipAfterPublish: false
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: NCS.DSS.AnonymiseBackup'
    inputs:
      pathtoPublish: $(build.artifactstagingdirectory)\Artifact\NCS.DSS.AnonymiseBackupPackages\
      artifactName: NCS.DSS.AnonymiseBackup
      publishLocation: container
  # Test NCS.DSS.AnonymiseBackup ARM template
  - template: AzureDevOpsTemplates/Build/dfc-arm-build.yml@dfc-devops
    parameters:
      ArmTemplateRoot: '$(System.DefaultWorkingDirectory)\Applications\NCS.DSS.AnonymiseBackup\Resources\ArmTemplates'
      AzureSubscription: SFA-DSS-DevTest

- job: BuildNCSDSSAnonymiseBackup
  displayName: Build and publish NCS.DSS.AnonymiseBackup container
  dependsOn: BuildAndTestPS
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    AppImageName: NCS.DSS.AnonymiseBackup:$(Build.SourceBranchName)-$(Build.BuildNumber)
  steps:
  - script: |
      cd ./Applications/NCS.DSS.AnonymiseBackup
      AppImageName=$(AppImageName)
      AppImageName=${AppImageName,,}
      docker build -t $(ContainerRegistryAdminUser).azurecr.io/$AppImageName .
    displayName: 'Build anonapp container'
  - script: |
      docker login -u $(ContainerRegistryAdminUser) -p $(ContainerRegistryPassword) $(ContainerRegistryAdminUser).azurecr.io
      cd ./Applications/NCS.DSS.AnonymiseBackup
      AppImageName=$(AppImageName)
      AppImageName=${AppImageName,,}
      docker push $(ContainerRegistryAdminUser).azurecr.io/$AppImageName
    displayName: 'Publish anonapp container'
- job: BuildRestoreAnonymisedBackup
  displayName: Test Restore ARM templates, build and publish container
  #dependsOn: BuildAndTestPS
  pool:
    vmImage: 'windows-2019'
  variables:
    RestoreImageBaseName: restoreanonymisebackup
    ArmTemplateRoot: '$(System.DefaultWorkingDirectory)\Applications\NCS.DSS.AnonymiseBackup\Resources\ArmTemplates'
    TestArmTemplateScriptUrl: https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/Test-ArmTemplate.ps1
    TestArmTemplateScriptFilePath: $(System.DefaultWorkingDirectory)\Test-ArmTemplate.ps1
  steps:
  - task: PowerShell@2
    name: DownloadTestArmTemplateScript
    displayName: 'Download Test-ArmTemplate script'
    inputs:
      targetType: 'inline'
      script: Invoke-WebRequest -Uri $(TestArmTemplateScriptUrl) -OutFile $(TestArmTemplateScriptFilePath)
  - task: AzurePowerShell@5
    displayName: 'Test Arm Template'
    inputs:
      azureSubscription: SFA-DSS-DevTest
      scriptType: filePath
      scriptPath: $(TestArmTemplateScriptFilePath)
      scriptArguments: -ParameterFile '$(ArmTemplateRoot)\restore-test-parameters.json' -TemplateFile '$(ArmTemplateRoot)\restore-template.json' -Verbose
      azurePowerShellVersion: LatestVersion
  - powershell: |
      $branchname = $env:sourcebranchname.ToLower();
      if ($env:sourcebranchname.Length -ge 190) { $branchname = $env:sourcebranchname.ToLower().Substring(0, 190) } else { $branchname = $env:sourcebranchname.ToLower() };
      Write-Host "##vso[task.setvariable variable=RestoreImageName]$(RestoreImageBaseName):$branchname-$(Build.BuildNumber)"
    displayName: 'Set restore container tag'
    env:
      sourcebranchname: '$(Build.SourceBranchName)' 
  - script: |
      cd ./Applications/NCS.DSS.AnonymiseBackup
      docker build -t $(ContainerRegistryAdminUser).azurecr.io/$(RestoreImageName) --file restore.Dockerfile .
    displayName: 'Build restore container'
  - script: |
      docker login -u $(ContainerRegistryAdminUser) -p $(ContainerRegistryPassword) $(ContainerRegistryAdminUser).azurecr.io
      cd ./Applications/NCS.DSS.AnonymiseBackup
      docker push $(ContainerRegistryAdminUser).azurecr.io/$(RestoreImageName)
    displayName: 'Publish restore container'