parameters:
- name: function_app
  displayName: Function App
  type: string
  default: acpla
  values:
  - acpla          # action plans
  - act            # actions
  - addr           # address
  - advde          # adviser details
  - col            # collections
  - cont           # contact details
  - cust           # customer 
  - digiden        # digital-identity
  - div            # diversity
  - employ         # employment-progression
  - goals          # goals
  - intac          # interaction
  - learn          # learning-progression
  - otcm           # outcomes
  - sess           # sessions
  - subs           # subscriptions
  - tran           # transfer
  - wchat          # web-chat

- name: version
  displayName: Function App / APIM Version
  type: string
  default: v1

- name: environment
  displayName: Environment Prefix
  type: string
  default: at
  values:
  - at
  - test
  - oat
  - pp
#  - prd

- name: azure_subscription
  displayName: Azure Subscription
  type: string
  default: SFA-CDH-Dev/Test
  values:
  - SFA-CDH-Dev/Test
  - SFA-DIG-PreProd
#  - SFA-DIG-Prod

trigger: none

pool:
  vmImage: "ubuntu-latest"

steps:
- bash: az --version
  displayName: 'Show Azure CLI version'

- bash: echo ${{parameters.environment}}
  displayName: 'Show Azure CLI version'

- task: AzureCLI@2
  displayName: 'Show all APIs and their versions for actionplans'
  inputs:
    azureSubscription: 'SFA-DSS-DevTest' # SFA-DSS-DevTest / SFA-DSS-PreProd / SFA-DSS-Prod
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az apim api list -g dss-test-shared-rg -n dss-test-shared-apim'

- task: AzureCLI@2
  displayName: 'Check if the API version exists'
  inputs:
    azureSubscription: 'SFA-DSS-DevTest' # SFA-DSS-DevTest / SFA-DSS-PreProd / SFA-DSS-Prod
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az apim api show --api-id actionplans-v3 -g dss-test-shared-rg --service-name dss-test-shared-apim'




# - bash: az apim api operation list -n dss-test-shared-apim --api-id actionplans -g dss-test-shared-rg
#   displayName: 'Show API versions for actionplans'